language: python

sudo: false

python:
  - 2.7
  - 3.4

env:
  matrix:
    - DB=mysql DJANGO="Django>=1.5,<1.6"
    - DB=postgres DJANGO="Django>=1.5,<1.6"
    - DB=sqlite DJANGO="Django>=1.5,<1.6"
    - DB=mysql DJANGO="Django>=1.6,<1.7"
    - DB=postgres DJANGO="Django>=1.6,<1.7"
    - DB=sqlite DJANGO="Django>=1.6,<1.7"
    - DB=mysql DJANGO="Django>=1.7,<1.8"
    - DB=postgres DJANGO="Django>=1.7,<1.8"
    - DB=sqlite DJANGO="Django>=1.7,<1.8"

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt
  - if [[ $DB == 'mysql' ]]; then pip install -q MySQL-python --use-mirrors; fi
  - if [[ $DB == 'postgres' ]]; then pip install -q psycopg2 --use-mirrors; fi

before_script:
  - mysql -e 'create database ice_address';
  - psql -U postgres -c 'create database ice_address;';

script: python setup.py test

matrix:
  exclude:
    - python: 3.4
      env: DB=mysql DJANGO="Django>=1.5,<1.6"
      env: DB=mysql DJANGO="Django>=1.6,<1.7"
      env: DB=mysql DJANGO="Django>=1.7,<1.8"
