language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

env:
  - DJANGO=Django==1.3 --use-mirrors
  - DJANGO=Django==1.4 --use-mirrors
  - DJANGO=Django==1.5 --use-mirrors

install:
  - pip install -q $DJANGO

script: python runtests.py
