language: python

python:
  - "3.3"
  - "2.7"

env:
  - DB=mysql DJANGO=Django==1.4
  - DB=mysql DJANGO=Django==1.5
  - DB=postgres DJANGO=Django==1.4
  - DB=postgres DJANGO=Django==1.5
  - DB=sqlite DJANGO=Django==1.4
  - DB=sqlite DJANGO=Django==1.5

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt
  - if [[ $DB == 'mysql' ]]; then pip install -q MySQL-python --use-mirrors; fi
  - if [[ $DB == 'postgres' ]]; then pip install -q psycopg2 --use-mirrors; fi

before_script:
  - if [[ $DB == 'mysql' ]]; then mysql -e 'create database ice_address'; fi
  - if [[ $DB == 'postgres' ]]; then psql -U postgres -c 'create database ice_address;'; fi

script: python setup.py test

matrix:
  exclude:
    - python: 3.3
      env: DB=mysql DJANGO=Django==1.4
    - python: 3.3
      env: DB=mysql DJANGO=Django==1.5
    - python: 3.3
      env: DB=postgres DJANGO=Django==1.4
    - python: 3.3
      env: DB=sqlite DJANGO=Django==1.4
