language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

env:
  - DJANGO=Django==1.3 --use-mirrors
  - DJANGO=Django==1.4 --use-mirrors
  - DJANGO=Django==1.5 --use-mirrors
  - DB=mysql
  - DB=postgres
  - DB=sqlite

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - if [[ $DB == 'mysql' ]]; then pip install -q MySQL-python --use-mirrors; fi
  - if [[ $DB == 'postgres' ]]; then pip install -q psycopg2 --use-mirrors; fi

before_script:
  - if [[ $DB == 'mysql' ]]; then mysql -e 'create database ice_address'; fi
  - if [[ $DB == 'postgres' ]]; then psql -U postgres -c 'create database ice_address;'; fi

script: python setup.py test
