language: python

python:
  - 2.7
  - 3.3

env:
  matrix:
    - DB=mysql DJANGO=Django==1.5
    - DB=postgres DJANGO=Django==1.5
    - DB=sqlite DJANGO=Django==1.5

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt
  - if [[ $DB == 'mysql' ]]; then pip install -q MySQL-python --use-mirrors; fi
  - if [[ $DB == 'postgres' ]]; then pip install -q psycopg2 --use-mirrors; fi

before_script:
  - mysql -e 'create database ice_address';
  - psql -U postgres -c 'create database ice_address;';

script: python setup.py test

matrix:
  exclude:
    - python: 3.3
      env: DB=mysql DJANGO=Django==1.5
